// <auto-generated />
using System;
using CargoCaptain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CargoCaptain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719103951_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CargoCaptain.Models.CargoEvent", b =>
                {
                    b.Property<int>("eventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventId"));

                    b.Property<int>("containerId")
                        .HasColumnType("int");

                    b.Property<string>("eventLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("eventTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("eventType")
                        .HasColumnType("int");

                    b.Property<string>("remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("eventId");

                    b.HasIndex("containerId");

                    b.ToTable("CargoEvents");
                });

            modelBuilder.Entity("CargoCaptain.Models.Container", b =>
                {
                    b.Property<int>("containerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("containerId"));

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<string>("containerNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("containerStatus")
                        .HasColumnType("int");

                    b.Property<int>("containerType")
                        .HasColumnType("int");

                    b.Property<string>("sealNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("containerId");

                    b.HasIndex("bookingId");

                    b.HasIndex("containerNumber")
                        .IsUnique();

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("CargoCaptain.Models.CustomsDeclaration", b =>
                {
                    b.Property<int>("declarationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("declarationId"));

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("calculatedDuty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("clearanceStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("declaredValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("hsCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("declarationId");

                    b.HasIndex("bookingId")
                        .IsUnique();

                    b.ToTable("CustomsDeclarations");
                });

            modelBuilder.Entity("CargoCaptain.Models.Employee", b =>
                {
                    b.Property<int>("employeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("employeeId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("employeeId");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            employeeId = 1,
                            email = "admin@cargocaptain.com",
                            firstName = "System",
                            lastName = "Admin",
                            phoneNumber = "+15550100",
                            userId = 1
                        },
                        new
                        {
                            employeeId = 2,
                            email = "forwarder@cargocaptain.com",
                            firstName = "Freight",
                            lastName = "Forwarder",
                            phoneNumber = "+15550101",
                            userId = 2
                        },
                        new
                        {
                            employeeId = 3,
                            email = "broker@cargocaptain.com",
                            firstName = "Customs",
                            lastName = "Broker",
                            phoneNumber = "+15550102",
                            userId = 3
                        },
                        new
                        {
                            employeeId = 4,
                            email = "operator@cargocaptain.com",
                            firstName = "Port",
                            lastName = "Operator",
                            phoneNumber = "+15550103",
                            userId = 4
                        });
                });

            modelBuilder.Entity("CargoCaptain.Models.FreightInvoice", b =>
                {
                    b.Property<int>("invoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("invoiceId"));

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<string>("currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("demurrageAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("freightCharges")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("invoiceStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("surchargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("totalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("invoiceId");

                    b.HasIndex("bookingId")
                        .IsUnique();

                    b.ToTable("FreightInvoices");
                });

            modelBuilder.Entity("CargoCaptain.Models.Login", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AssociatedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            AssociatedName = "System Admin",
                            Password = "HASHED_PASSWORD_PLACEHOLDER_FOR_ADMIN",
                            Role = 0
                        },
                        new
                        {
                            UserId = 2,
                            AssociatedName = "Freight Forwarder Client",
                            Password = "HASHED_PASSWORD_PLACEHOLDER_FOR_FORWARDER",
                            Role = 1
                        },
                        new
                        {
                            UserId = 3,
                            AssociatedName = "Customs Broker Client",
                            Password = "HASHED_PASSWORD_PLACEHOLDER_FOR_BROKER",
                            Role = 2
                        },
                        new
                        {
                            UserId = 4,
                            AssociatedName = "Port Operator Client",
                            Password = "HASHED_PASSWORD_PLACEHOLDER_FOR_OPERATOR",
                            Role = 3
                        });
                });

            modelBuilder.Entity("CargoCaptain.Models.ShipmentBooking", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingId"));

                    b.Property<string>("bookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("bookingStatus")
                        .HasColumnType("int");

                    b.Property<string>("consigneeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("destinationPort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("originPort")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("shipperName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("bookingId");

                    b.HasIndex("bookingNumber")
                        .IsUnique();

                    b.ToTable("ShipmentBookings");
                });

            modelBuilder.Entity("CargoCaptain.Models.CargoEvent", b =>
                {
                    b.HasOne("CargoCaptain.Models.Container", "Container")
                        .WithMany("CargoEvents")
                        .HasForeignKey("containerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("CargoCaptain.Models.Container", b =>
                {
                    b.HasOne("CargoCaptain.Models.ShipmentBooking", "ShipmentBooking")
                        .WithMany("Containers")
                        .HasForeignKey("bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("CargoCaptain.Models.CustomsDeclaration", b =>
                {
                    b.HasOne("CargoCaptain.Models.ShipmentBooking", "ShipmentBooking")
                        .WithOne("CustomsDeclaration")
                        .HasForeignKey("CargoCaptain.Models.CustomsDeclaration", "bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("CargoCaptain.Models.Employee", b =>
                {
                    b.HasOne("CargoCaptain.Models.Login", "Login")
                        .WithOne("Employee")
                        .HasForeignKey("CargoCaptain.Models.Employee", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("CargoCaptain.Models.FreightInvoice", b =>
                {
                    b.HasOne("CargoCaptain.Models.ShipmentBooking", "ShipmentBooking")
                        .WithOne("FreightInvoice")
                        .HasForeignKey("CargoCaptain.Models.FreightInvoice", "bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShipmentBooking");
                });

            modelBuilder.Entity("CargoCaptain.Models.Container", b =>
                {
                    b.Navigation("CargoEvents");
                });

            modelBuilder.Entity("CargoCaptain.Models.Login", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CargoCaptain.Models.ShipmentBooking", b =>
                {
                    b.Navigation("Containers");

                    b.Navigation("CustomsDeclaration");

                    b.Navigation("FreightInvoice");
                });
#pragma warning restore 612, 618
        }
    }
}
